### ISSUE TITLE
Stripe checkout page blank

### ISSUE THREAD

**Issue by walqid** [Jaspero/fireshop#201] opened 2020-02-01 09:18 UTC
The `/checkout` route route displays a blank page. When the removing the `hideLayout: true` property from the `/checkout` route in `app-routing.module.ts`, the page displays properly.

Is there another underlying reason for this error?

**Comment by flauc** [comment] 2020-03-11 22:16
It's very strange those that flag is only used to hide the navigation in the layout. We're also unable to reproduce this, checkout seems to work fine on the example site. I'm closing this for now.

**Closed by flauc** 2020-03-11 22:16 UTC
